import { NodeHandler, NodeResult } from '../types';
import { resolveVariables } from '../variables';
import { sendEmail } from '../../services/email.service';
import { generateAIMessage } from '../ai-service';

function normalizeBraces(text: string): string {
    return text.replace(/\{([^{}]+)\}/g, '{{$1}}');
}

/**
 * EMAIL node — sends a personalized email via the user's connected
 * email account (SMTP or OAuth: Gmail/Microsoft).
 *
 * Config:
 *   - subject: string with {firstName}/{{firstName}} placeholders
 *   - message / body / text: plaintext body, same placeholder syntax
 *   - html: optional pre-rendered HTML
 *   - aiEnabled: when true, body is generated by /ai/message using
 *     the same profile + campaign context the send-message node uses
 *     (subject is always template-driven — short, deterministic).
 *
 * Skip semantics (success, no send):
 *   - no recipient (email-finder returned null AND lead.email is null)
 *
 * Failure semantics (node fails, lead progresses):
 *   - no EmailAccount connected, SMTP auth fails, OAuth token revoked.
 */
export const emailNode: NodeHandler = async (ctx, config): Promise<NodeResult> => {
    const { lead, userId, campaignId, storedOutputs, campaign, aiContext } = ctx;

    const recipient = (storedOutputs['email-finder']?.email as string | undefined) || lead.email;
    if (!recipient) {
        console.log('[EMAIL] No recipient address for lead — skipping send.');
        return { success: true, output: { sent: false, skipReason: 'no_recipient' } };
    }

    const rawSubject = config.subject || 'Quick question';
    const rawBody = config.message || config.body || config.text || 'Hi {firstName},';
    const aiEnabled = config.aiEnabled || false;
    const tone = config.tone || campaign?.toneOverride || 'professional';
    const cta = config.cta || campaign?.cta || 'connect';

    const resolveCtx = {
        lead: { firstName: lead.firstName, lastName: lead.lastName },
        storedOutputs,
    };
    // Template subject is the fallback; an AI-generated subject (when
    // aiEnabled + AI returns one) takes precedence below.
    let subject = resolveVariables(normalizeBraces(rawSubject), resolveCtx);

    let body: string;
    if (aiEnabled) {
        console.log('[EMAIL] Generating AI subject + body...');
        try {
            const profileName = `${lead.firstName || ''} ${lead.lastName || ''}`.trim() || 'User';
            const pv = storedOutputs['profile-visit'] || {};
            const aiResult = await generateAIMessage({
                profileName,
                profileHeadline: pv.headline || pv.jobTitle || lead.headline || lead.jobTitle || undefined,
                company:  pv.company  || lead.company  || undefined,
                jobTitle: pv.jobTitle || lead.jobTitle || undefined,
                location: pv.location || lead.location || undefined,
                about:    pv.about    || lead.aboutInfo || undefined,
                experience: pv.experience || [],
                education:  pv.education  || [],
                connectionContext: campaign?.objective || undefined,
                campaignDescription: campaign?.campaignDescription || campaign?.objective || undefined,
                tone,
                cta,
                persona: campaign?.persona || aiContext?.userContext?.persona || undefined,
                valueProposition: campaign?.valueProp || aiContext?.userContext?.valueProp || undefined,
                aiStrategy: aiContext?.aiStrategy,
                userContext: aiContext?.userContext,
                // Phase C
                channel: 'email',
                aiPrompt: config.aiPrompt,
                campaignProgress: (ctx as any).campaignProgress,
                messageHistory: (ctx as any).messageHistory,
            });
            const aiBody = aiResult.message;
            if (aiBody && aiBody.length > 10) {
                body = aiBody;
                if (aiResult.subject && aiResult.subject.length > 0) {
                    subject = aiResult.subject;
                    console.log(`[EMAIL] AI subject: "${subject}"`);
                }
                console.log('[EMAIL] AI body generated:', body.substring(0, 60) + '...');
            } else {
                console.log('[EMAIL] AI output invalid, using template fallback');
                body = resolveVariables(normalizeBraces(rawBody), resolveCtx);
            }
        } catch (err: any) {
            console.error('[EMAIL] AI generation failed, using template fallback:', err.message);
            body = resolveVariables(normalizeBraces(rawBody), resolveCtx);
        }
    } else {
        body = resolveVariables(normalizeBraces(rawBody), resolveCtx);
    }

    console.log(`[EMAIL] Sending to ${recipient}: "${subject.substring(0, 60)}..."`);

    const result = await sendEmail({
        userId,
        leadId: lead.id,
        campaignId,
        to: recipient,
        subject,
        text: body,
        html: config.html,
    });

    if (!result.success) {
        console.error(`[EMAIL] Send failed: ${result.error}`);
        return { success: false, error: result.error, output: { sent: false, error: result.error } };
    }

    import('../../services/crm-events')
        .then(({ emitCrmEvent }) => emitCrmEvent({ event: 'lead.messaged', userId, campaignId, leadId: lead.id, meta: { channel: 'email' } }))
        .catch((err: any) => console.error('[EMAIL] emit lead.messaged failed:', err?.message));

    // Capture the recipient into the S3 confirmed-email dataset (fire-and-forget).
    // A successful relay accept is a weaker signal than a contact-card read (no
    // bounce tracking yet), so it's tagged 'email-sent' for later weighting.
    import('../../services/email-dataset.service')
        .then(({ recordConfirmedEmail }) => recordConfirmedEmail({
            email: recipient,
            source: 'email-sent',
            firstName: lead.firstName, lastName: lead.lastName,
            company: lead.company, jobTitle: lead.jobTitle, headline: lead.headline,
            linkedinUrl: lead.linkedinUrl, connectionDegree: (lead as any).connectionDegree ?? null,
            userId, campaignId, leadId: lead.id,
        }))
        .catch(() => {});

    return {
        success: true,
        output: { sent: true, messageId: result.messageId, to: recipient, subject, aiGenerated: aiEnabled },
    };
};
