import nodemailer, { Transporter } from 'nodemailer';
import { prisma } from '@repo/db';
import { encrypt, decrypt } from '../utils/crypto';
import * as google from './oauth/google.service';
import * as microsoft from './oauth/microsoft.service';

export interface SendEmailArgs {
    userId: string;
    to: string;
    subject: string;
    /** Plaintext body. The HTML version is generated by wrapping in <p> tags
     *  unless `html` is also provided — keeps templates simple. */
    text: string;
    html?: string;
    /** Optional override (campaigns use this to set reply-to = lead's known
     *  inbound channel; for outreach, the from-address handles replies). */
    replyTo?: string;
    /** Set for campaign sends so the resulting Message row joins the audit
     *  log under the correct campaign. */
    campaignId?: string;
    leadId?: string;
    /** True when the body was AI-generated — tags the Message row source 'AI'
     *  so the Messages tab shows the AI badge + rationale. */
    aiGenerated?: boolean;
    /** Deterministic "why this message" rationale (see ai-rationale.ts). */
    rationale?: string;
}

export interface SendEmailResult {
    success: boolean;
    messageId?: string;
    error?: string;
}

/**
 * Build a nodemailer transporter from the user's stored SMTP credentials.
 * Throws (caller handles) if no EmailAccount is connected — the EMAIL node
 * surfaces this as a node-level failure, not a campaign crash.
 *
 * Provider tag drives auth flow:
 *   - 'smtp'           → SMTP host+port+user+pass (decrypted at send time)
 *   - 'gmail-oauth'    → future: Gmail API client
 *   - 'microsoft-oauth' → future: Graph API client
 */
async function getTransporter(userId: string): Promise<{
    transporter: Transporter;
    fromEmail: string;
    fromName: string | null;
}> {
    const account = await prisma.emailAccount.findUnique({ where: { userId } });
    if (!account) throw new Error('No email account connected for user');

    if (account.provider !== 'smtp') {
        throw new Error(`Email provider '${account.provider}' is not yet implemented`);
    }

    if (!account.smtpHost || !account.smtpPort || !account.smtpUser || !account.smtpPass) {
        throw new Error('SMTP credentials incomplete');
    }

    const password = decrypt(account.smtpPass);
    const transporter = nodemailer.createTransport({
        host: account.smtpHost,
        port: account.smtpPort,
        secure: account.smtpSecure,
        auth: { user: account.smtpUser, pass: password },
    });

    return {
        transporter,
        fromEmail: account.fromEmail,
        fromName: account.fromName,
    };
}

export async function sendEmail(args: SendEmailArgs): Promise<SendEmailResult> {
    try {
        const account = await prisma.emailAccount.findUnique({ where: { userId: args.userId } });
        if (!account) throw new Error('No email account connected');

        let messageId: string;

        // Provider dispatch — same record shape, different transports.
        // OAuth providers go through their respective APIs (Gmail v1,
        // Graph) so the user's auth context is exactly what they
        // consented to; SMTP keeps the nodemailer code path for users
        // on custom domains.
        if (account.provider === 'gmail-oauth') {
            messageId = await google.sendViaGmail({
                userId: args.userId,
                to: args.to,
                subject: args.subject,
                text: args.text,
                html: args.html,
                replyTo: args.replyTo,
                fromName: account.fromName,
            });
        } else if (account.provider === 'microsoft-oauth') {
            messageId = await microsoft.sendViaGraph({
                userId: args.userId,
                to: args.to,
                subject: args.subject,
                text: args.text,
                html: args.html,
                replyTo: args.replyTo,
                fromName: account.fromName,
            });
        } else {
            const { transporter, fromEmail, fromName } = await getTransporter(args.userId);
            const from = fromName ? `"${fromName}" <${fromEmail}>` : fromEmail;
            const html = args.html || args.text.split('\n\n').map(p => `<p>${p}</p>`).join('\n');
            const info = await transporter.sendMail({
                from,
                to: args.to,
                replyTo: args.replyTo,
                subject: args.subject,
                text: args.text,
                html,
            });
            messageId = info.messageId;
        }

        await prisma.emailAccount.update({
            where: { userId: args.userId },
            data: { lastSendAt: new Date(), lastError: null },
        });

        // Persist for the inbox/audit view. Channel = 'email' so the
        // LinkedIn-DM inbox filter keeps these out.
        if (args.leadId) {
            await prisma.message.create({
                data: {
                    userId: args.userId,
                    leadId: args.leadId,
                    campaignId: args.campaignId,
                    direction: 'SENT',
                    channel: 'email',
                    subject: args.subject,
                    content: args.text,
                    messageId,
                    source: args.aiGenerated ? 'AI' : (args.campaignId ? 'CAMPAIGN' : 'MANUAL'),
                    rationale: args.rationale || null,
                },
            });
        }

        return { success: true, messageId };
    } catch (err: any) {
        const msg = err?.message || String(err);
        await prisma.emailAccount
            .update({ where: { userId: args.userId }, data: { lastError: msg } })
            .catch(() => undefined);
        return { success: false, error: msg };
    }
}

/**
 * Used by POST /email-account/test. Same transport, no Message row, fixed
 * subject/body so a user can verify SMTP creds without sending real outreach.
 */
export async function sendTestEmail(userId: string): Promise<SendEmailResult> {
    const account = await prisma.emailAccount.findUnique({ where: { userId } });
    if (!account) return { success: false, error: 'No email account connected' };
    // sendEmail() picks the right transport for the user's current provider,
    // so a single call works for SMTP / Gmail OAuth / Microsoft OAuth.
    return sendEmail({
        userId,
        to: account.fromEmail,
        subject: `Qampi: ${account.provider} connection works`,
        text: `This is a Qampi test email via ${account.provider}.\n\nIf you received this, your email account is connected and the EMAIL node is ready to use in campaigns.`,
    });
}

/**
 * Convenience wrapper used by the API route. Encrypts the password before
 * upsert; callers never touch the crypto helpers directly.
 */
export interface UpsertEmailAccountInput {
    fromEmail: string;
    fromName?: string;
    smtpHost: string;
    smtpPort: number;
    smtpUser: string;
    smtpPass: string;
    smtpSecure?: boolean;
}

export async function upsertEmailAccount(userId: string, input: UpsertEmailAccountInput) {
    const encryptedPass = encrypt(input.smtpPass);
    return prisma.emailAccount.upsert({
        where: { userId },
        create: {
            userId,
            provider: 'smtp',
            fromEmail: input.fromEmail,
            fromName: input.fromName,
            smtpHost: input.smtpHost,
            smtpPort: input.smtpPort,
            smtpUser: input.smtpUser,
            smtpPass: encryptedPass,
            smtpSecure: input.smtpSecure ?? false,
        },
        update: {
            provider: 'smtp',
            fromEmail: input.fromEmail,
            fromName: input.fromName,
            smtpHost: input.smtpHost,
            smtpPort: input.smtpPort,
            smtpUser: input.smtpUser,
            smtpPass: encryptedPass,
            smtpSecure: input.smtpSecure ?? false,
            lastError: null,
        },
    });
}
